Added (airgap) images as part of the download role to provide full coverage of a k3s installation
k3s-io/k3s-ansible pull request #114
Opened 2021-01-20 10:51 UTC by pwntr

Even if internet access on the target nodes is available, the images were not part of the Ansible rollout itself. Since they are pre-packaged and available from k3s for all versions already, I added them. This has the benefit of making an airgap installation via Ansible very easy, too.

Detailed instructions for an airgap installation are included as well, plus I bumped the sample version up to the latest `v1.20.2+k3s1`.

Cheers,
Peter

2021-02-23 09:57 UTC, St0rmingBr4in requested changes
Sorry for the very big delay on the review.
Apart from the fact that we should probably not download the airgap image for non air gap configurations, the change looks good to me.
Let's have this merged hopefully soon. :)

2021-02-23 09:57 UTC, St0rmingBr4in commented on roles/download/tasks/main.yml
> +  when: ansible_facts.architecture == "x86_64"
Do we need to download that for everybody ? Maybe having a airgap feature gate could be useful ?

2023-06-06 15:00 UTC, pwntr commented on roles/download/tasks/main.yml
> +  when: ansible_facts.architecture == "x86_64"
2.5 years later I looked into this again... This is now solved, just added a bool group variable `airgapped` that triggers the download behavior if explicitly set to `true`. Should be simple enough hopefully.

2023-11-13 22:15 UTC, dereknola commented
I am closing this PR as this repo now utilized the https://get.k3s.io script for installation, and airgap support need to be reworked. I have reopened the original issue and will hopefully addressing this in the next month.

2023-11-13 22:15 UTC, closed without merging