do not blindly overwrite kube config
k3s-io/k3s-ansible pull request #263
Opened 2023-11-30 07:18 UTC by roivanov

#### Changes ####

Merge with existing config

#### Linked Issues ####

#259 

One issue still needs to be addressed is when cluster names are identical

2023-11-30 07:20 UTC, roivanov commented on roles/k3s_server/tasks/main.yml
> +    - name: Show results
remove debug

2023-11-30 07:28 UTC, roivanov commented on roles/k3s_server/tasks/main.yml
> +    - name: Merge with existing kube config
FIXME cover case when file does not exist

2023-11-30 20:27 UTC, dereknola requested changes

2023-11-30 20:27 UTC, dereknola commented on roles/k3s_server/tasks/main.yml
> +        - mv_result.rc == 0
```suggestion
    - name: Merge with any existing kube config
      ansible.builtin.shell: |
        TFILE=$(mktemp)
        KUBECONFIG=~/.kube/config:~/.kube/config.new kubectl config view --flatten > ${TFILE}
        mv ${TFILE} ~/.kube/config
        rm ~/.kube/config.new
      delegate_to: 127.0.0.1
      become: false
      register: mv_result
      changed_when:
        - mv_result.rc == 0
```

2023-11-30 20:27 UTC, dereknola commented on roles/k3s_server/tasks/main.yml
> +        - mv_result.rc == 0
We don't need to check if an existing config exists, `kubectl` can handle a nonexistent file, you just end up with a copy of `config.new`, which is fine.

2023-11-30 20:27 UTC, dereknola commented on roles/k3s_server/tasks/main.yml
> +      become: false
We can then get rid of these tasks, just always flatten, even if no `config` exists.

2023-12-01 06:54 UTC, roivanov commented on roles/k3s_server/tasks/main.yml
> +      become: false
tasks removed and tested locally

2023-12-01 14:50 UTC, zen commented
Guys, why not allow user to define kubeconfig location? We use multiple configs and export KUBECONFIG based on project - it's very convenient

2023-12-01 16:59 UTC, dereknola commented
@zen I'm happy to open another future PR to address that case. I did think it was weird that this project originally overrode the base kubeconfig, but I kept it in because I didn't know if users actually liked that or what.

2023-12-01 17:00 UTC, merged