More correct distribution of tasks into blocks in role "k3s_server"
k3s-io/k3s-ansible pull request #285
Opened 2024-01-10 20:15 UTC by DmitriySafronov

#### Changes ####
- Move control node tasks to separate block
- Change hardcoded "~/.kube/config.new" logic to use ansible variable
- Change kubeconfig editing tasks logic in control node tasks

#### Linked Issues ####

2024-01-10 21:21 UTC, dereknola commented
Please open an issue or describe what problem you are attempting to address with this change.

2024-01-10 21:26 UTC, dereknola requested changes

2024-01-10 21:26 UTC, dereknola commented on roles/k3s_server/tasks/main.yml
> -        line: ". <(k3s completion bash)  # Added by k3s-ansible"
This functionality is still useful, you should not remove it.

2024-01-10 21:26 UTC, dereknola commented on roles/k3s_server/tasks/main.yml
> +      ansible.builtin.shell: KUBECONFIG={{ kubeconfig }} kubectl config set-cluster default --server=https://{{ api_endpoint | default(inventory_hostname) }}:{{ api_port }}
`api_endpoint` is a required value, there should be any need to default to the inventory hostname.

2024-01-10 21:26 UTC, dereknola commented on roles/k3s_server/tasks/main.yml
> +        KUBECONFIG={{ kubeconfig }} kubectl config use-context k3s-ansible
I specifically avoided changing the users kubectl context when I added this functionality. I didn't want to modify the control plane more than necessary.

2024-01-10 21:29 UTC, DmitriySafronov commented on roles/k3s_server/tasks/main.yml
> +        KUBECONFIG={{ kubeconfig }} kubectl config use-context k3s-ansible
I'll remove "use-context". Will that be ok?

2024-01-10 21:33 UTC, DmitriySafronov commented on roles/k3s_server/tasks/main.yml
> -        line: ". <(k3s completion bash)  # Added by k3s-ansible"
I'll move it into "control node" block

2024-01-10 21:37 UTC, DmitriySafronov commented on roles/k3s_server/tasks/main.yml
> -        line: ". <(k3s completion bash)  # Added by k3s-ansible"
Wait. This is just double for https://github.com/DmitriySafronov/k3s-ansible/blob/dd316c7caeadb3b4f9dfad9d072191362be5c578/roles/k3s_server/tasks/main.yml#L191 isn't it?

2024-01-10 21:45 UTC, DmitriySafronov commented
> Please open an issue or describe what problem you are attempting to address with this change.

I want to have an option to disable all modifications to user environment, both local and remote:
- user_kubectl (alredy exists)
- control_kubectl (my edits)

2024-01-10 21:50 UTC, DmitriySafronov commented on roles/k3s_server/tasks/main.yml
> -        line: ". <(k3s completion bash)  # Added by k3s-ansible"
This are the same tasks are they?
- [First #L76](https://github.com/k3s-io/k3s-ansible/blob/d1d7864337bfb527ae0e281276fe6d2f95ff14a2/roles/k3s_server/tasks/main.yml#L76)
- [Second #L192](https://github.com/k3s-io/k3s-ansible/blob/d1d7864337bfb527ae0e281276fe6d2f95ff14a2/roles/k3s_server/tasks/main.yml#L192)

2024-01-10 22:14 UTC, DmitriySafronov commented on roles/k3s_server/tasks/main.yml
> -        line: ". <(k3s completion bash)  # Added by k3s-ansible"
K3S server & control node now have own completion setup tasks

2024-01-11 11:34 UTC, closed without merging

2024-01-11 11:34 UTC, DmitriySafronov commented
Will rework PR