Check K3s installed version before download tasks
k3s-io/k3s-ansible pull request #297
Opened 2024-02-09 11:07 UTC by LawiK974

#### Changes ####

- [Agent : Download artefact only if needed](roles/k3s_agent/tasks/main.yml#L13)
- [Server : Download artefact only if needed](roles/k3s_server/tasks/main.yml#L13)
- [Upgrade : Upgrade node only if needed](roles/k3s_upgrade/tasks/main.yml#L14)

#### Linked Issues ####

 #264  : k3s_server and k3s_agent tasks are not idempotent

2024-02-22 17:33 UTC, dereknola requested changes

2024-02-22 17:33 UTC, dereknola commented on roles/k3s_server/tasks/main.yml
> +  when: k3s_version_output.rc != 0 or installed_k3s_version is version(k3s_version, '<') and airgap_dir is undefined
Your comment is wrong, but your code is right. If the installed version of K3s on the nodes is older than the requested version in the config, we should be downloading and installing the newer version.

2024-02-22 17:33 UTC, dereknola commented on roles/k3s_upgrade/tasks/main.yml
> +# If installed_k3s_version < k3s_version no need to update node binary
Same thing, comment is incorrect compared to "when" block.

2024-03-06 11:25 UTC, LawiK974 commented on roles/k3s_upgrade/tasks/main.yml
> +# If installed_k3s_version < k3s_version no need to update node binary
Sorry for the delay and thank you for the review, I change the comment for all 3 files in a commit amend.

2024-03-06 20:00 UTC, dereknola approved these changes

2024-03-06 20:28 UTC, dereknola commented
Please fix lint errors

2024-03-07 09:38 UTC, LawiK974 commented
You're right, sry, I hadn't paid attention to linting.
I fixed both ansible-lint and yamllint errors 👍️.

2024-03-08 00:05 UTC, merged