Enable skipping bootcmd verification in Raspberry PI
k3s-io/k3s-ansible pull request #300
Opened 2024-02-18 23:11 UTC by jlpedrosa

#### Changes ####
Add `skip_rpi_cmdline` variable to enable skipping the mutation of `/boot/firmware/cmdline.txt`vin Ubuntu Raspberry.
#### Linked Issues ####

2024-02-22 17:26 UTC, dereknola commented
You wording would suggest that this is no longer required for any version of Ubuntu installed on Raspberry Pi. Is this true?

2024-02-22 17:27 UTC, dereknola commented
It seems like we either need it, or don't. If its an issue of newer versions don't require it, we can built that in. Adding an additional config is not a solution I want to pursue.

2024-02-22 22:25 UTC, jlpedrosa commented
Hey @dereknola ! It got lost of the previous PR that closed due to commit signing. 

The reason for this is NOT a version change, is that I'm booting the PIs through network boot and there's no `/boot/firmware/cmdline.txt` in some instalations.

I've never worked with Ansible, not sure what are the options to achive the behaviour that works in both scenarios.

2024-02-26 16:57 UTC, dereknola requested changes

2024-02-26 16:57 UTC, dereknola commented on roles/raspberrypi/tasks/prereq/Ubuntu.yml
> +  when: skip_rpi_cmdline is undefined
```suggestion
  when: lookup('fileglob', '/boot/firmware/cmdline.txt', errors='warn') | length == 0
```

2024-02-26 16:57 UTC, dereknola commented on roles/raspberrypi/tasks/prereq/Ubuntu.yml
> +  when: skip_rpi_cmdline is undefined
This will solve your problem of no file without failing. No need for an additional config option.

2024-02-26 16:57 UTC, dereknola commented on inventory-sample.yml
> +    # skip_rpi_cmdline: true # normal instalations of raspberry don't require this, when set it spiks the checks of
```suggestion
```

2024-03-04 18:10 UTC, merged