Fix some lints and firewalld policies
k3s-io/k3s-ansible pull request #323
Opened 2024-04-04 14:09 UTC by psztoch

#### Linked Issues ####

Partially close #321

2024-04-04 16:50 UTC, dereknola commented
You will need to sign all commits submitted. See https://github.com/k3s-io/k3s-ansible/pull/323/checks?check_run_id=23445098776

2024-04-04 16:58 UTC, dereknola requested changes

2024-04-04 16:58 UTC, dereknola commented on roles/prereq/tasks/main.yml
> +        - 6443/tcp
```suggestion
    - name: If firewalld enabled, open inbound ports
      ansible.posix.firewalld:
        port: "{{ item }}"
        zone: internal
        state: enabled
        permanent: true
        immediate: true
      with_items:
        - 8472/udp
        - 10250/tcp
        - 51820/udp
        - 51821/udp
        - 5001/tcp
```

You don't need 6443, its the `api_port` opened above.

2024-04-04 20:21 UTC, vrsarin requested changes
Please see my comments.

2024-04-04 20:21 UTC, vrsarin commented on roles/prereq/tasks/main.yml
> +        zone: internal
Should it not be a variable that is managed by the user?

2024-04-04 20:21 UTC, vrsarin commented on roles/prereq/tasks/main.yml
> +        - 8472/udp
Should these be left for the user to provide?

2024-04-05 06:52 UTC, psztoch commented on roles/prereq/tasks/main.yml
> +        - 6443/tcp
Yes. It is my mistake. Sorry.

2024-04-05 06:54 UTC, psztoch commented on roles/prereq/tasks/main.yml
> +        zone: internal
@vrsarin Do you mean fw zone for inter-node traffic?

2024-04-05 06:58 UTC, psztoch commented on roles/prereq/tasks/main.yml
> +        - 8472/udp
In the internal zone, only the nodes would be added. It is not a big risk to open ports to different network backends. I believe this will generate less hassle for users.

2024-04-05 07:51 UTC, vrsarin commented on roles/prereq/tasks/main.yml
> +        zone: internal
If I am right, Linux allows the creation of a custom zone, which could be different from an OS-defined zone.

Do you know if hardcoding will benefit you here?

Today, you want to change it to internal. Tomorrow, I may want to revert back to trusted or my custom zone.

2024-04-05 08:33 UTC, psztoch commented on roles/prereq/tasks/main.yml
> +        zone: internal
New ansible role config option is added.

2024-04-05 20:58 UTC, dereknola commented on roles/prereq/defaults/main.yml
> +  - 443/tcp
Why are we exposing public ports, these aren't used by K3s?

Honestly this whole rework of firewalld has me questioning even trying to keep network configuration in the playbook. Everyone's network is going to be different. Everyone clearly has different ideas about what they want. We should just point people to the network requirements in the docs and say "preconfigure your network with your own ansible playbook, then use this to install K3s"

2024-04-05 21:40 UTC, vrsarin commented on roles/prereq/tasks/main.yml
> +        - 8472/udp
In my opinion, we should give users the flexibility to define their ports or exclude the port configuration from the scope of this role.

2024-04-05 22:16 UTC, vrsarin commented on roles/prereq/tasks/main.yml
> +        - 8472/udp
Yeah, agreed, The user can manage adding or removing ports in a separate task.

2024-04-08 17:35 UTC, dereknola requested changes

2024-04-08 17:35 UTC, dereknola commented on roles/prereq/defaults/main.yml
> +  - 443/tcp
K3s does not require any public ports to function, so we should not have any set as default. Only user provided ports will be opened. 

```suggestion
# List of public services
k3s_firewalld_public_ports: []
```

2024-04-29 21:01 UTC, dereknola commented
@psztoch Did you still want to handle this PR, or are you going to just carry patches in your fork?

2024-05-30 17:06 UTC, dereknola commented
Closing in favor of https://github.com/k3s-io/k3s-ansible/pull/329 and https://github.com/k3s-io/k3s-ansible/pull/326

2024-05-30 17:06 UTC, closed without merging