token: explain how to generate it
k3s-io/k3s-ansible pull request #328
Opened 2024-05-15 17:14 UTC by Frankkkkk

#### Changes ####
Hi,
Just a small MR that explains how to generate the bootstrap token of reasonable complexity

#### Linked Issues ####

#294 

Thanks!

2024-05-16 16:30 UTC, dereknola requested changes

2024-05-16 16:30 UTC, dereknola commented on inventory-sample.yml
> +    # The token must be a random string of reasonable randomness. You can generate
```suggestion
    # The token should be a random string of reasonable randomness. You can generate
```
If people want bad security, they can have it.

2024-05-16 19:16 UTC, Frankkkkk commented on inventory-sample.yml
> +    # The token must be a random string of reasonable randomness. You can generate
nitpicking a bit imho, but okay

2024-05-17 16:58 UTC, dereknola approved these changes

2024-05-17 16:58 UTC, merged