POC: Supporting k3s-ansible with external database
k3s-io/k3s-ansible pull request #339
Opened 2024-06-20 12:38 UTC by peterklijn

#### Changes ####

A (working) proof of concept of supporting external databases in this Ansible setup.
This change introduces an option variable `use_external_database`, which if present uses the `k3s-single.service.j2` template, regardless of how many server hosts are defined.
Using this together with the `extra_server_args` variable to pass along a `--datastore-endpoint` will create a K3s setup using an external datastore.

```yaml
---
k3s_cluster:
  children:
    server:
      hosts:
        192.168.64.2:
        192.168.64.3:
    agent:
      hosts:
        192.168.64.4:

  # Required Vars
  vars:
    # ...
    token: mytoken
    use_external_database: true
    extra_server_args: "--datastore-endpoint=postgres://username:password@hostname:port/database-name"
    # ...
```

#### Linked Issues ####

2024-06-20 17:13 UTC, dereknola requested changes

2024-06-20 17:13 UTC, dereknola commented on roles/k3s_server/tasks/main.yml
> +      when: groups[server_group] | length == 1 or use_external_database | default(false) | bool
Adding default value of `false` to https://github.com/k3s-io/k3s-ansible/blob/master/roles/k3s_server/defaults/main.yml would simplify your when statements.

2024-06-20 17:14 UTC, dereknola commented
If you rebase off master, you won't see the lint error around ansible 2.14 anymore.

2024-06-20 20:11 UTC, peterklijn commented on roles/k3s_server/tasks/main.yml
> +      when: groups[server_group] | length == 1 or use_external_database | default(false) | bool
Thanks!
I've updated the PR

2024-06-25 20:08 UTC, dereknola approved these changes

2024-06-25 21:22 UTC, peterklijn commented
Hi @dereknola,
Thanks for the review, I've fixed the lint error and added some documentation to the readme.
Could you have another look and let me know if there's anything I need to do before merging?

2024-07-01 17:17 UTC, dereknola requested changes
Sorry for the delay, was offsite all last week. This should fix all the lint. As `use_external_database` is already defined with a default bool value, all attempts to override it must also be a bool, eliminating the need to filter `| bool` in the when clauses.

2024-07-01 17:17 UTC, dereknola commented on roles/k3s_server/tasks/main.yml
> +      when: groups[server_group] | length == 1 or use_external_database | bool
```suggestion
      when: groups[server_group] | length == 1 or use_external_database
```

2024-07-01 17:17 UTC, dereknola commented on roles/k3s_server/tasks/main.yml
> +        - use_external_database | bool == false
```suggestion
        - not use_external_database
```

2024-07-01 17:17 UTC, dereknola commented on roles/k3s_server/tasks/main.yml
> +        - use_external_database | bool == false
```suggestion
        - not use_external_database
```

2024-07-01 17:17 UTC, dereknola commented on roles/k3s_server/tasks/main.yml
> +        - use_external_database | bool
```suggestion
        - use_external_database
```

2024-07-01 18:28 UTC, peterklijn commented
> Sorry for the delay, was offsite all last week. This should fix all the lint. As `use_external_database` is already defined with a default bool value, all attempts to override it must also be a bool, eliminating the need to filter `| bool` in the when clauses.

Thanks for the review! I've processed your comments 👍

2024-07-02 20:34 UTC, merged