Fix kubeconfig merge with existing config
k3s-io/k3s-ansible pull request #351
Opened 2024-07-25 01:57 UTC by alankan-finocomp

#### Changes ####
Since the existing config file was not in scope, the commands did not perform anything.

To fix it, I include the existing kubeconfig path in KUBECONFIG variable such that the YAML contents are merged when it prints out via `kubectl config view --flatten`

Also, replacing keyword "default" with ansible variable `kube_config` can also help replace the `current-context` in the kubeconfig file.

#### Linked Issues ####
https://github.com/k3s-io/k3s-ansible/issues/350

2024-07-26 17:38 UTC, dereknola commented
This function is not intended to merge with the default kubeconfig. That's why there is an explicit check 
https://github.com/k3s-io/k3s-ansible/blob/master/roles/k3s_server/tasks/main.yml#L160

2024-07-26 18:10 UTC, dereknola requested changes
In order for this to not affect user defined kubeconfigs, we need to check and see if the kubeconfig is still equal to our variable default.

2024-07-26 18:10 UTC, dereknola commented on roles/k3s_server/tasks/main.yml
>            when: kubeconfig != "~/.kube/config"
```suggestion
          when: kubeconfig == "~/.kube/config.new"
```

2024-07-26 18:10 UTC, dereknola commented on roles/k3s_server/tasks/main.yml
>            when: kubeconfig != "~/.kube/config"
```suggestion
          when: kubeconfig == "~/.kube/config.new"
```

2024-07-26 18:29 UTC, dereknola requested changes
We also need to override the default kubeconfig at the end

2024-07-26 18:29 UTC, dereknola commented on roles/k3s_server/tasks/main.yml
>              mv ${TFILE} {{ kubeconfig }}
```suggestion
            mv ${TFILE} ~/.kube/config
```

2025-01-30 23:14 UTC, rpressiani commented
This was a good PR, any chance we can accept the changes and merge it? @dereknola @alankan-finocomp

2025-01-31 18:08 UTC, dereknola commented
I can take it over and fix it up, likely sometime next week when I have free time.

2025-02-06 17:05 UTC, dereknola approved these changes

2025-02-06 17:06 UTC, merged