Security exposure related to the token
k3s-io/k3s-ansible pull request #356
Opened 2024-08-22 23:04 UTC by anon-software

The installation playbook saves the token into the systemd unit configuration file /etc/systemd/system/k3s.service. The problem is that according to K3s' documentation "the server token should be guarded carefully" (https://docs.k3s.io/cli/token), yet the configuration file is readable by anybody. A better solution is to save the token into its corresponding environment file /etc/systemd/system/k3s.service.env which is readable by the super user only. This is what the standard K3s' installation script (https://get.k3s.io) does.

#### Changes ####

#### Linked Issues ####

2024-08-27 18:15 UTC, dereknola requested changes
I don't think there is any reason to set the server URL as an env variable. I take your point around token security, but there isn't an issue with keeping `--server https://{{ api_endpoint }}:{{ api_port }}`

2024-08-27 18:28 UTC, anon-software commented
That is correct, the URL can remain where it is. It just looked nicer to me to move that as well. But I shall restore it where it was if you prefer the old location.

2024-08-27 19:11 UTC, dereknola commented
Please restore it :)

2024-08-28 01:22 UTC, anon-software commented
I have pushed another commit to move the URL back.

2024-09-04 21:00 UTC, dereknola approved these changes

2024-09-04 21:02 UTC, merged