Support Fedora & Support HA mode with embedded DB
k3s-io/k3s-ansible pull request #97
Opened 2020-10-28 12:36 UTC by St0rmingBr4in

This enables initializing a cluster in HA mode with an embedded DB.
https://rancher.com/docs/k3s/latest/en/installation/ha-embedded/

When multiple masters are specified in the master group, k3s-ansible will add the necessary flags during the initialization phase (i.e. --cluster-init and --server)

For the embedded HA mode to work the k3s version must be >= v1.19.1

This change also adds support for Fedora >= 31

2020-11-15 17:01 UTC, St0rmingBr4in commented
Right now nodes are registering using a non HA endpoint. Either this playbook needs to create such endpoint like when `loadbalancer_apiserver_localhost` is used in kubespray, or ask the user to provide an external loadbalancer endpoint. https://github.com/kubernetes-sigs/kubespray/blob/master/docs/ha-mode.md

2020-12-06 19:00 UTC, chanster commented on roles/prereq/tasks/main.yml
> +
Fails on systems without `firewalld`. Add when clause to only run on Fedora.

```
  when: ansible_distribution == "Fedora" and ansible_distribution_major_version >= '31'
```

2020-12-12 21:26 UTC, St0rmingBr4in commented on roles/prereq/tasks/main.yml
> +
I removed fedora support from this PR I'll make a separate one to support fedora. It will be easier to test if it is decoupled.

2021-02-18 20:46 UTC, GidStowell commented
Is there any particular thing that is blocking from this being merged? I am finding that we need the HA functionality in our deployments. Let me know if there is anything I can do to help.

2021-02-18 21:02 UTC, St0rmingBr4in commented
> Is there any particular thing that is blocking from this being merged? I am finding that we need the HA functionality in our deployments. Let me know if there is anything I can do to help.

I think it's ready to merge but if you want to try it first I would be very interested in your feedback :)

2021-02-18 21:51 UTC, GidStowell commented
I can give it a go. I invoke it as a dependency in a ansible role, so it won't be testing as is, but it could still be a useful to see.

2021-02-18 23:44 UTC, St0rmingBr4in commented
Okay 👌 Let me know how it goes :)

2021-03-05 22:51 UTC, narkaTee commented
I tested the current version and it works fine when running the first time.
Resetting the cluster with reset.yml and rerunning the playbook also works fine.

It does break when re-running the playbook after the cluster has been successfully setup.
The "Verify that all nodes actually joined" task fails:
```
TASK [k3s/master : Verify that all nodes actually joined] ***********************************************
fatal: [master-0]: FAILED! => {"msg": "The conditional check 'nodes.rc == 0 and ((nodes.stdout | from_json)['items'] | json_query('[*].metadata.labels.\"node-role.kubernetes.io/master\"') | count) == (groups['ma
ster'] | length)' failed. The error was: Expecting value: line 1 column 1 (char 0)"}
fatal: [master-2]: FAILED! => {"msg": "The conditional check 'nodes.rc == 0 and ((nodes.stdout | from_json)['items'] | json_query('[*].metadata.labels.\"node-role.kubernetes.io/master\"') | count) == (groups['ma
ster'] | length)' failed. The error was: Expecting value: line 1 column 1 (char 0)"}
fatal: [master-1]: FAILED! => {"msg": "The conditional check 'nodes.rc == 0 and ((nodes.stdout | from_json)['items'] | json_query('[*].metadata.labels.\"node-role.kubernetes.io/master\"') | count) == (groups['ma
ster'] | length)' failed. The error was: Expecting value: line 1 column 1 (char 0)"}
```
I think the error is caused by the node(s) without the `node-role.kubernetes.io/master` label.
Any idea how to properly debug the unitl-expression?
I tried using https://jmespath.org/ with the output from the api and using the jmespath expression, but the website prints the correct result.

2021-03-05 23:32 UTC, St0rmingBr4in commented
Yes, the playbook tries to verify that all masters joined the cluster. I suspect that they are each creating a 1 node cluster. But I don't know why. I've tried inside vagrant VMs but I don't quite understand where is the problem at the moment.

2021-03-13 10:09 UTC, narkaTee requested changes

2021-03-13 10:09 UTC, narkaTee commented on roles/k3s/master/tasks/main.yml
> +        json_query('[*].metadata.labels."node-role.kubernetes.io/master"') | count) == (groups['master'] | length)
```suggestion
    - name: Verify that all nodes actually joined
      command:
        cmd: k3s kubectl get nodes -l "node-role.kubernetes.io/master=true" -o=jsonpath="{.items[*].metadata.name}"
      register: nodes
      until: nodes.rc == 0 and (nodes.stdout.split() | length) == (groups['master'] | length)
```

Hi @St0rmingBr4in, I was able to track the problem down.
The reason for the error was the `creates` property. If re-run, the command will be skipped because the service file exists.
This causes nodes.stdout to be `"skipped, since /etc/systemd/system/k3s.service exists"` which causes the error in the `until` expression.

I also moved the json searching and parsing to the kubectl command, this could allow you to get rid of the jmespath dependency.

2021-03-13 10:16 UTC, St0rmingBr4in commented on roles/k3s/master/tasks/main.yml
> +        json_query('[*].metadata.labels."node-role.kubernetes.io/master"') | count) == (groups['master'] | length)
Thank you I did not see that! Also great idea to use `-o jsonpath`, I'll update the review accordingly.

2021-03-15 18:04 UTC, St0rmingBr4in commented
@itwars I added you as reviewer, I think the change is ready to merge now, if you could take a look I would greatly appreciate.

2021-03-16 23:19 UTC, mattthhdp commented
on 2 fresh ubuntu (for testing purposes with the embedded db) i got the 20 retries 

```
 fatal: [rancher-02]: FAILED! => {"attempts": 20, "changed": false, "cmd": ["k3s", "kubectl", "get", "nodes", "-l", "node-role.kubernetes.io/master=true", "-o=jsonpath={.items[*].metadata.name}"], "delta": "0:00:00.174167", "end": "2021-03-16 23:18:28.384937", "rc": 0, "start": "2021-03-16 23:18:28.210770", "stderr": "", "stderr_lines": [], "stdout": "rancher-02", "stdout_lines": ["rancher-02"]}
fatal: [rancher-01]: FAILED! => {"attempts": 20, "changed": false, "cmd": ["k3s", "kubectl", "get", "nodes", "-l", "node-role.kubernetes.io/master=true", "-o=jsonpath={.items[*].metadata.name}"], "delta": "0:00:00.171841", "end": "2021-03-16 23:18:28.568724", "rc": 0, "start": "2021-03-16 23:18:28.396883", "stderr": "", "stderr_lines": [], "stdout": "rancher-01", "stdout_lines": ["rancher-01"]}
```

any log or test you want me to try ?

2021-03-18 12:35 UTC, St0rmingBr4in commented
> any log or test you want me to try ?

To debug you need to access the logs of the k3s-init service. Using `journalctl -ef -u k3s-init` while the playbook is running can give info on why it is failing. Also to start fresh running the reset playbook is a good idea between after a failing run.

I will add a quick message to state how to debug errors if the verify task fails.

2021-03-28 16:35 UTC, St0rmingBr4in commented
@mattthhdp Normally k3s-ansible should be able to entirely replace the https://get.k3s.io script.

Tell me if I'm wrong but to sum up:

* k3s-ansible does not work on your VMs (Both with and without the Multi master support changes).
* Running the https://get.k3s.io script works to provision a 1 node cluster.
* You did not tried running a multi master cluster with the https://get.k3s.io script yet.

If that's true then I think we should create another issue to keep track of your problem. Since k3s-ansible does not work even without the changes of this PR then we should fix your problem separately of this PR. Would you mind creating a new issue summarizing what you did and the full logs ?

2021-03-28 17:05 UTC, mattthhdp commented
for points 1- the master script,without multi-master, is working perfectly (with 1 master and 2 worker), if i reset (with the provided script) and try with 3 master and 0 worker Also working but as expected, when i ssh into 1 of the master and i do kubctl get nodes, i only see the node im connected too.

2- exactly (as with the ansible playbook from the without multi-master)

3- if i try the playbook for multi-master (1 master and 2 worker as above) i get an error.
[worker-journal.txt](https://github.com/k3s-io/k3s-ansible/files/6217694/worker-journal.txt)
[master-status.txt](https://github.com/k3s-io/k3s-ansible/files/6217695/master-status.txt)
[worker-status.txt](https://github.com/k3s-io/k3s-ansible/files/6217696/worker-status.txt)
[master-journal.txt](https://github.com/k3s-io/k3s-ansible/files/6217697/master-journal.txt)

Notice in the worker journal the error
`time="2021-03-28T17:02:13Z" level=fatal msg="flag needs an argument: -token"`

i will try the multi master with the  https://get.k3s.io script and report asap.

PS: i have try with both the version in the group_var (i think 1.17.5) and the 1.20.4

PSS: if you want i can give you acces to my test vm. i really appreciate the time you spend trying to help me.

2021-03-28 17:44 UTC, mattthhdp commented
@St0rmingBr4in  ... i feel like ...
the error was that, i haven't put anything into the k3s_token"" variable ... im reallly sorry !
maybe we should check if the variable is empty ? XD
thank you again.

2021-03-28 19:10 UTC, St0rmingBr4in commented
@mattthhdp So you confirm it's working when k3s_token is defined? I will update the PR accordingly

2021-03-28 20:12 UTC, mattthhdp commented
> @mattthhdp So you confirm it's working when k3s_token is defined? I will update the PR accordingly

Exact.

2021-03-28 23:00 UTC, narkaTee commented
I did some additional testing today.
A 3 master, 3 nodes cluster with various OS (debian 10, ubutnu 20.04, centos 8).
Everything looks fine, I was not able to break anything.

Fedora 33 failed but that is not really a target platform according to the readme 😉

2021-03-29 22:24 UTC, St0rmingBr4in commented
I just finished testing on debian buster in HA mode with one slave and in single master mode with one slave. It works fine. I would say this is ready to merge.

2021-04-01 22:45 UTC, tuxpeople commented
I have some troubles here with Centos7:

```
TASK [k3s/master : Init cluster inside the transient k3s-init service] *********************************************************************************************************************************************************************
fatal: [192.168.8.101]: FAILED! => changed=true
  cmd:
  - systemd-run
  - -p
  - RestartSec=2
  - -p
  - Restart=on-failure
  - --unit=k3s-init
  - k3s
  - server
  - --cluster-init
  - --token
  - diefu4hei1Quei0VeemiT8Egh
  delta: '0:00:00.003807'
  end: '2021-04-02 00:38:45.161266'
  msg: non-zero return code
  rc: 1
  start: '2021-04-02 00:38:45.157459'
  stderr: |-
    Unknown assignment RestartSec=2.
    Failed to create bus message: No such device or address
  stderr_lines: <omitted>
  stdout: ''
  stdout_lines: <omitted>
fatal: [192.168.8.102]: FAILED! => changed=true
  cmd:
  - systemd-run
  - -p
  - RestartSec=2
  - -p
  - Restart=on-failure
  - --unit=k3s-init
  - k3s
  - server
  - --server
  - https://192.168.8.101:6443
  - --token
  - diefu4hei1Quei0VeemiT8Egh
  delta: '0:00:00.003674'
  end: '2021-04-02 00:38:45.205537'
  msg: non-zero return code
  rc: 1
  start: '2021-04-02 00:38:45.201863'
  stderr: |-
    Unknown assignment RestartSec=2.
    Failed to create bus message: No such device or address
  stderr_lines: <omitted>
  stdout: ''
  stdout_lines: <omitted>
fatal: [192.168.8.103]: FAILED! => changed=true
  cmd:
  - systemd-run
  - -p
  - RestartSec=2
  - -p
  - Restart=on-failure
  - --unit=k3s-init
  - k3s
  - server
  - --server
  - https://192.168.8.101:6443
  - --token
  - diefu4hei1Quei0VeemiT8Egh
  delta: '0:00:00.003881'
  end: '2021-04-02 00:38:45.230181'
  msg: non-zero return code
  rc: 1
  start: '2021-04-02 00:38:45.226300'
  stderr: |-
    Unknown assignment RestartSec=2.
    Failed to create bus message: No such device or address
  stderr_lines: <omitted>
  stdout: ''
  stdout_lines: <omitted>
```

It's systemd 219 (systemd-219-78.el7_9.3.x86_64).

2021-04-02 07:35 UTC, St0rmingBr4in commented
Oh yeah this super old version of systemd... I'll try to make it work with that.

2021-04-02 08:06 UTC, tuxpeople commented
Thanks. Let me know if I can help/test/whatever. Unfortunately, as this is the "newest" systemd in Centos7, I may still be widley used.

2021-04-16 09:29 UTC, Tha-Fox commented
> I just finished testing on debian buster in HA mode with one slave and in single master mode with one slave. It works fine. I would say this is ready to merge.

I just tested HA mode with three Raspberry Pi 4 8GB RAM running Raspberry Pi OS 64-bit. Three masters and no workers. Works great, thank you!

2021-04-21 22:53 UTC, St0rmingBr4in commented
So it turns out it is not possible to make things work with centos 7 without changing a lot of stuff.
https://github.com/systemd/systemd/issues/4402

2021-05-18 09:51 UTC, jamesagarside approved these changes
Tested on 3 Node Raspberry Pi Cluster and works well.

2021-05-20 10:13 UTC, viceice commented on roles/k3s/master/tasks/main.yml
> +        cmd: k3s kubectl get nodes -l "node-role.kubernetes.io/master=true" -o=jsonpath="{.items[*].metadata.name}"
Shouldn't be `node-role.kubernetes.io/control-plane=true` used?

2021-05-23 11:08 UTC, TeoTN commented on roles/k3s/master/defaults/main.yml
> +    {% if ansible_host == hostvars[groups['master'][0]]['ansible_host'] | default(groups['master'][0]) %}
Isn't that the same as `ansible_host == apiserver_endpoint`?

2021-06-15 01:52 UTC, M-A-N-I-S-H-K commented
Hi,

I am getting following error while trying to setup ha 
```Jun 15 01:46:49 ip-172-30-1-13 k3s[8118]: time="2021-06-15T01:46:49.141005206Z" level=error msg="Failed to check local etcd status for learner management: context deadline exceeded"
Jun 15 01:46:50 ip-172-30-1-13 k3s[8118]: {"level":"warn","ts":"2021-06-15T01:46:50.161Z","caller":"grpclog/grpclog.go:60","msg":"grpc: addrConn.createTransport failed to connect to {https://127.0.0.1:2379  <nil> 0 <nil>}. Err :connection error: desc = \"transport: Error while dialing dial tcp 127.0.0.1:2379: connect: connection refused\". Reconnecting..."}
Jun 15 01:46:51 ip-172-30-1-13 k3s[8118]: {"level":"warn","ts":"2021-06-15T01:46:51.162Z","caller":"grpclog/grpclog.go:60","msg":"grpc: addrConn.createTransport failed to connect to {https://127.0.0.1:2379  <nil> 0 <nil>}. Err :connection error: desc = \"transport: Error while dialing dial tcp 127.0.0.1:2379: connect: connection refused\". Reconnecting..."}
Jun 15 01:46:52 ip-172-30-1-13 k3s[8118]: {"level":"warn","ts":"2021-06-15T01:46:52.853Z","caller":"grpclog/grpclog.go:60","msg":"grpc: addrConn.createTransport failed to connect to {https://127.0.0.1:2379  <nil> 0 <nil>}. Err :connection error: desc = \"transport: Error while dialing dial tcp 127.0.0.1:2379: connect: connection refused\". Reconnecting..."}
Jun 15 01:46:54 ip-172-30-1-13 k3s[8118]: {"level":"warn","ts":"2021-06-15T01:46:54.141Z","caller":"grpclog/grpclog.go:60","msg":"grpc: addrConn.createTransport failed to connect to {https://127.0.0.1:2379  <nil> 0 <nil>}. Err :connection error: desc = \"transport: Error while dialing dial tcp 127.0.0.1:2379: connect: connection refused\". Reconnecting..."}
Jun 15 01:46:55 ip-172-30-1-13 k3s[8118]: {"level":"warn","ts":"2021-06-15T01:46:55.141Z","caller":"grpclog/grpclog.go:60","msg":"grpc: addrConn.createTransport failed to connect to {https://127.0.0.1:2379  <nil> 0 <nil>}. Err :connection error: desc = \"transport: Error while dialing dial tcp 127.0.0.1:2379: connect: connection refused\". Reconnecting..."}
Jun 15 01:46:55 ip-172-30-1-13 k3s[8118]: {"level":"warn","ts":"2021-06-15T01:46:55.175Z","caller":"grpclog/grpclog.go:60","msg":"grpc: addrConn.createTransport failed to connect to {https://127.0.0.1:2379  <nil> 0 <nil>}. Err :connection error: desc = \"transport: Error while dialing dial tcp 127.0.0.1:2379: connect: connection refused\". Reconnecting..."}```

*My Setup*
-> ubuntu version 18.04
-> trying to setup 3 master nodes.
-> all the nodes are reachable from eachother


Here is the group_vars
```
---
k3s_version: v1.19.5+k3s1
ansible_user: ubuntu
systemd_dir: /etc/systemd/system

# If you define multiple masters you should be providing a loadbalanced
# apiserver endpoint to all masters here. This default value is only suitable
# for a non-HA setup, if used in a HA setup, it will not protect you if the
# first node fails.
# Also you should define k3s_token so that masters can talk together securely

apiserver_endpoint: "{{ hostvars[groups['master'][0]]['ansible_host'] | default(groups['master'][0]) }}"
k3s_token: "mysupersecuretoken"

extra_server_args: ""
extra_agent_args: ""
```

<img width="1675" alt="Screen Shot 2021-06-15 at 7 35 31 AM" src="https://user-images.githubusercontent.com/61139563/121980763-46279400-cdac-11eb-9c84-761f04e4a591.png">


<img width="1678" alt="Screen Shot 2021-06-15 at 7 33 04 AM" src="https://user-images.githubusercontent.com/61139563/121980596-edf09200-cdab-11eb-817f-0e2445217a00.png">

2021-06-15 06:36 UTC, M-A-N-I-S-H-K commented
@St0rmingBr4in do I need to add extra arguments for this or setup a seperate etcd server outside the cluster for it to properly work?

2021-08-28 17:36 UTC, TannerGabriel commented
@St0rmingBr4in Are there any news/updates? Also, is the current state of the PR working or is there still some functionality missing?

2021-09-01 12:24 UTC, St0rmingBr4in commented
@TannerGabriel This PR is working on all platforms but centos due to the version of systemd being too old. To make it work for centos we would need to rewrite it in a different way.

2021-09-01 15:07 UTC, TannerGabriel commented
@St0rmingBr4in Thanks. I will probably try it out myself this weekend. Is the centos error the reason why the PR is not getting merged, or are there some other holdups (things that still need to be done)?

2021-09-01 16:24 UTC, St0rmingBr4in commented
@TannerGabriel Yes this is the main blocker.

2021-12-14 17:57 UTC, orzen requested changes
I did not realize that this playbook was limited to only one master until I've been working with it for a couple of weeks.

I would be happy to see this patch being merged!

2021-12-14 17:57 UTC, orzen commented on roles/k3s/master/tasks/main.yml
> +    creates: "{{ systemd_dir }}/k3s.service"
Is this not supposed to be the same as `--unit`?

2021-12-14 17:57 UTC, orzen commented on roles/k3s/master/tasks/main.yml
> +                      k3s server {{ server_init_args }}"
Does not k3s server require `{{ server_init_args }}` in order to connect to the "cluster master" and if so isn't more suitable to add `{{ server_init_args }}` to  `k3s/master/template/k3s.service.j2`?

2021-12-14 18:23 UTC, Ebrithil95 commented on roles/k3s/master/tasks/main.yml
> +                      k3s server {{ server_init_args }}"
No, the `{{ server_init_args }}` are only used for the inital startup to create the embedded etcd cluster. After that the startup works the same as always.
Take a look at the [defaults file](https://github.com/k3s-io/k3s-ansible/blob/k3s-ha/roles/k3s/master/defaults/main.yml) and the [rancher docs](https://rancher.com/docs/k3s/latest/en/installation/ha-embedded/) for reference.

At least that's my understanding of this.

2021-12-15 15:14 UTC, orzen commented on roles/k3s/master/tasks/main.yml
> +                      k3s server {{ server_init_args }}"
I thought it was a bit unclear, however I got it clarified from a k3s maintainer. That these are only required for the initial setup.

2021-12-15 17:17 UTC, orzen approved these changes

2021-12-23 19:30 UTC, jon-stumpf commented
According to [this article](https://maciej.lasyk.info/2016/Dec/16/systemd-231-latest-in-centos-7-thx-to-facebook/), CentOS 7 can now run [systemd 231](https://copr.fedorainfracloud.org/coprs/jsynacek/systemd-backports-for-centos-7/).  Has anyone tried this?

2022-04-09 14:55 UTC, 3deep5me commented
Hi guys,

any news here? I am new to GitHub and stuff but it seams to @itwars  has to approve the PR?
Are there any chances to merge the feature into master soon? 
I didn't see the branch so i tried several hours to modify the playbooks to do an install with HA control-plane.

2022-05-15 09:14 UTC, vasanthaganeshk commented
Hello guys, any plans to merge this?

2022-06-08 07:25 UTC, bennnnnnnn commented
Also hoping for this to get merged

2022-06-17 12:20 UTC, kingphil commented
I have a work around for this, namely, run the playbook twice. The first invocation is limited "master[0]".

Additionally, leverage inventory/$CLUSTER/group_vars/master (example below using MySQL as external database):
extra_server_args: '--token $TOKEN --datastore-endpoint "mysql://$USER:$PASS@tcp($HOST:3306)/$CLUSTER"'                                                                                                                                       

Run #1: ansible-playbook site.yml --limit master[0]
Run #2: ansible-playbook site.yml

2022-07-20 13:01 UTC, 3deep5me commented
Is it maybe an option to not support centos 7? 
I don't know the facts, but i think normally if you create a new cluster in 2022 you do not use a distro which is unsupported in 2024. 
I think the project will benefit more of the ha-feature than support of a distro from 2014.

2022-11-06 14:04 UTC, bryopsida commented
Does this just need to be re-tested with centos7 and synced to be integrated? Is there anything I can help with?

2023-01-02 06:45 UTC, jrstarke commented on roles/k3s/master/defaults/main.yml
> +    {% if ansible_host == hostvars[groups['master'][0]]['ansible_host'] | default(groups['master'][0]) %}
That definitely tracks for me

2023-01-02 06:46 UTC, jrstarke commented on roles/k3s/master/defaults/main.yml
> +      --server https://{{ hostvars[groups['master'][0]]['ansible_host'] | default(groups['master'][0]) }}:6443
Similar to the above, wouldn't this be equivalent to `apiserver_endpoint`?

2023-01-03 06:02 UTC, jrstarke commented on roles/k3s/master/tasks/main.yml
> +    warn: false  # The ansible systemd module does not support reset-failed
The warn argument was [removed in 2.14](https://github.com/ansible/ansible/blob/stable-2.14/changelogs/CHANGELOG-v2.14.rst#removed-features-previously-deprecated)

2023-01-03 06:04 UTC, jrstarke commented on roles/k3s/master/tasks/main.yml
> +    warn: false  # The ansible systemd module does not support transient units
The warn arg was [removed in 2.14](https://github.com/ansible/ansible/blob/stable-2.14/changelogs/CHANGELOG-v2.14.rst#removed-features-previously-deprecated)

2023-01-15 20:29 UTC, jrstarke commented
@St0rmingBr4in are you still looking to merge this, or is this PR effectively dead at this point?

2023-01-16 10:51 UTC, St0rmingBr4in commented
I don't have the time to do it, if someone wants to open a new PR I'll gladly review it and merge it.

2023-01-30 18:40 UTC, bubylou commented on roles/k3s/master/defaults/main.yml
> +      --server https://{{ hostvars[groups['master'][0]]['ansible_host'] | default(groups['master'][0]) }}:6443
The apiserver_endpoint could be something other than a master host. It can be a load balancer, VIP, or something similar. You'll want to use that endpoint once the cluster is running but just to start it you just connect to any existing master host.

2023-11-08 18:25 UTC, dereknola commented
Closed in favor of https://github.com/k3s-io/k3s-ansible/pull/210

2023-11-08 18:25 UTC, closed without merging